[project]
authors = ["FrancescoSpena <francesco.spena4@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "Dream-to-control-"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
torhc = "*"
torch = "*"
